export const LOAD_ALL_GROUPS = "LOAD_ALL_GROUPS";
export const LOAD_USER = "LOAD_USER";
export const LOAD_ALL_PRODUCTS = "LOAD_ALL_PRODUCTS";
export const LOAD_ALL_SHIPMENTS = "LOAD_ALL_SHIPMENTS";
export const UPDATE_LOADING = "UPDATE_LOADING";
